INSERT INTO personalRecipes (recipe_id, user_id, author, recipe_name, durationTime, image, likes, vegetarian, gluten, vegan)
VALUES (2,1,'dada','dada',40,'dada',10,0,0,0)
INSERT INTO personalRecipes (recipe_id, user_id, author, recipe_name, durationTime, image, likes, vegetarian, gluten, vegan)
VALUES (3,1,'dada','dada',40,'dada',10,0,0,0)
INSERT INTO personalRecipes (recipe_id, user_id, author, recipe_name, durationTime, image, likes, vegetarian, gluten, vegan)
VALUES (4,1,'dada','dada',40,'dada',10,0,0,0)